### ISSUE TITLE
"Invaid variable assigned" error

### ISSUE THREAD

**Issue by wabiloo** [gdavila/easyVmaf#1]
Hi,
Love the idea of this tool, so I decided to try it on my own content.

I ran the following command line:
```python3 easyVmaf.py -r /mnt/assets/sources/ucho/ucho.mp4 -d /mnt/assets/incumbent/ucho/214-video-5727-3960kbps.mp4 -sw 2```

After a few "Getting frames info" and "Getting stream info" outputs, the following error was raise:

```Traceback (most recent call last):
  File "easyVmaf.py", line 93, in <module>
    myVmaf = vmaf(main, reference, loglevel=loglevel, subsample=n_subsample, model=model)
  File "/home/ec2-user/easyVmaf/Vmaf.py", line 107, in __init__
    self.ffmpegQos = FFmpegQos(self.main.videoSrc, self.ref.videoSrc, self.loglevel)
  File "/home/ec2-user/easyVmaf/FFmpeg.py", line 90, in __init__
    self.main = inputFFmpeg(main, input_id =0)
  File "/home/ec2-user/easyVmaf/FFmpeg.py", line 188, in __init__
    self.name = varname.varname()
  File "/usr/local/lib/python3.7/site-packages/varname.py", line 45, in varname
    f"Invaid variable assigned: {ast.dump(target)!r}"
varname.VarnameAssignedToInvalidVariable: Invaid variable assigned: "Attribute(value=Name(id='self', ctx=Load()), attr='main', ctx=Store())"```

**Comment by gdavila** [comment]
Hi. It seems a issue with `varname`. Could you check if it is installed? if not try `pip3 install python-varname`. 
Otherwise, could you provide me the varname version you have installed?  `pip3 list | grep varname `

**Comment by wabiloo** [comment]
Yep, I definitely have it installed. Version 0.1.1

**Comment by gdavila** [comment]
ok. I can reproduce the issue. I was using an old old `varname` version (0.0.3). Let me check what is happening with 0.1.1

**Comment by gdavila** [comment]
I've removed the dependency of `varname` completely and updated the repo. Actually, I was not implementing the features that I had in mind when I used the varname package so is cleaner now. 

Try the last commit [249d86b](https://github.com/gdavila/easyVmaf/commit/249d86b7f353c654aca47a99337579e30413f89e), the issue should be solved.

**Comment by gdavila** [comment]
I will close this issue given that the varname dependency was removed. If there is still some other issue please let me know.
