### ISSUE TITLE
libvmaf encountered an error ... Invalid argument

### ISSUE THREAD

**Issue by cdgriffith** [gdavila/easyVmaf#10]
On both Linux (Ubuntu 20.04.1 LTS) and Windows I am getting the same error trying to compare the reference material and would appreciate any help!

Command: `python easyVmaf.py -d video_samples\BBB_sampleA_distorted.mp4 -r video_samples\BBB_reference_10s.mp4 -verbose`

```
[Parsed_libvmaf_2 @ 0x67a64c0] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
```

Linux details: 
Using Python 3.8.5
FFmpeg built with libvmaf: 1.5.2
Models from https://github.com/Netflix/vmaf commit d03342f5bdcb46acc7643e9c91c0285b2d49931b

Full Log [easyVMAF errors.log](https://github.com/gdavila/easyVmaf/files/5630549/easyVMAF.errors.log)

Changes to `config.py` to make it cross platform compatible: 

```python
import shutil
from pathlib import Path

models = Path("/usr/local/share/model/")
if not models.exists():
    models = Path(__file__).parent.absolute() / "models"

ffmpeg = shutil.which('ffmpeg')
ffprobe = shutil.which('ffprobe')
vmaf_4K = models / 'vmaf_4k_v0.6.1.pkl'
vmaf_HD = models / 'vmaf_v0.6.1.pkl'
vmaf_HDneg = models / 'vmaf_v0.6.1neg.pkl'
```

Then had to change name of `FFmpeg.py` as that conflicts with the `which` command  when run from that directory.

**Comment by gdavila** [comment]
Hola,

As far I could see, there was some changes on vmaf models names on the last VMAF commits (see [VMAF#722](https://github.com/Netflix/vmaf/pull/722)). You should change the model names on `config.py` file with the new ones, i.e:

```
vmaf_4K = models / 'vmaf_4k_v0.6.1.pkl'
vmaf_HD = models / 'vmaf_float_v0.6.1.pkl'
vmaf_HDneg = models / 'vmaf_float_v0.6.1neg.pkl'
```

I tested it on my Linux machine and it works. Let me know if it does for you.

**Comment by cdgriffith** [comment]
Ah ha, Thank you!

It was combo of that and then some path issues due to how stuff was not quoted in the filter and me running the models from a weird directory. 

[FFmpeg.py line 163](https://github.com/gdavila/easyVmaf/blob/master/FFmpeg.py#L163) updates  (refactored to ffmpeg_commands.py)
```python 
        log_path = log_path.replace("\\", "/") 
        self.vmafFilter = [f'[{main}][{ref}]libvmaf=log_fmt={log_fmt}:model_path=\'{model_path}\':phone_model={phone_model}:n_subsample={subsample}:log_path=\'{log_path}\':psnr=1:ssim=1']
```

config.py updates to be cross compatible (due to how ffmpeg treats paths) 
```python
vmaf_4K = str(models / 'vmaf_4k_v0.6.1.pkl').replace("\\", "/")
vmaf_HD = str(models / 'vmaf_float_v0.6.1.pkl').replace("\\", "/")
vmaf_HDneg = str(models / 'vmaf_float_v0.6.1neg.pkl').replace("\\", "/")
```

Working on both Windows and Linux 😄
