### ISSUE TITLE
Vmaf filter doesn't properly use all cores

### ISSUE THREAD

**Issue by Sohex** [gdavila/easyVmaf#11]
In theory the ffmpeg vmaf filter defaults to using all available logical processors, in practice it doesn't look like that's happening. It's really an upstream issue, but there's a massive speedup if you specify n_threads in the filter params.

**Comment by gdavila** [comment]
Thanks @Sohex for the feedback. Would that be the behaviour on all OS?

**Comment by Sohex** [comment]
Not sure, I'm seeing it on Ubuntu, I haven't checked it on anything else.

**Comment by gdavila** [comment]
Thanks for helping to improve this tool. Really appreciated. I've added the `-threads (int)` option.
