### ISSUE TITLE
VMAF Scores for phone and HD models are the same for 240p at bitrate 100kbps

### ISSUE THREAD

**Issue by minhkstn** [gdavila/easyVmaf#13]
Hi,

I am calculating the VMAF scores for my video with your tool. I have two videos in this [link](https://drive.google.com/drive/folders/1c9dN__49-vMMRvqAuGgl7ae-xiUMPCZt?usp=sharing).

- Reference video: `Beauty_3840x2160_1080p_50M.mp4` with 1080p resolution

- Distorted video: `Beauty_3840x2160_100kkbps_240p.mp4` with 240p resolution

I run this command to get the score
`python3 easyVmaf.py -r Beauty_3840x2160_1080p_50M.mp4 -d Beauty_3840x2160_100kkbps_240p.mp4`
and
`python3 easyVmaf.py -model HD -phone -r Beauty_3840x2160_1080p_50M.mp4 -d Beauty_3840x2160_100kkbps_240p.mp4`
Both results I got are **37.948279865277776**

Do you think the score on phone should be higher?
Thank you for your time.

**Comment by gdavila** [comment]
Could you run the cmds again  with the option  `-verbose` enabled and  share the output. Specifically, I want to check what are the ffmpeg commands that are being executed. 

The phone model should be higher  yes - but what mainly calls my attention is that booth scores give exactly the same output score.

**Comment by minhkstn** [comment]
Hi,
I realize the Phone mode is set to False though I add `-phone`. That's why the output is the same.
Here's the output

1. HD model

> Computing VMAF... 
=======================================
Distorted: ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p.mp4 @ 30.0 fps | 426 240
Reference: ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_1080p_50M.mp4 @ 30.0 fps | 1920 1080
Offset: 0
Model: HD
Phone: False
loglevel: verbose
subsample: 1
output_fmt: json
=======================================
/usr/local/bin/ffmpeg -y -hide_banner -stats -loglevel verbose  -i "./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p.mp4" -i "./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_1080p_50M.mp4" -map 0:v -map 1:v -lavfi "[0:v]scale=1920:1080:flags=bicubic[input0_0];[input0_0]fps=fps=30.0[input0_1];[1:v]fps=fps=30.0[input1_0];[input0_1][input1_0]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p_vmaf.json:psnr=1:ssim=1" -f null -
=======================================
VMAF computed
=======================================
offset:  0  | psnr:  None
VMAF score (arithmetic mean):  37.948279865277776
VMAF score (harmonic mean):  37.42345926938661
VMAF output File Path:  ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p_vmaf.json

2. HD model with PHONE
> Computing VMAF... 
=======================================
Distorted: ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p.mp4 @ 30.0 fps | 426 240
Reference: ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_1080p_50M.mp4 @ 30.0 fps | 1920 1080
Offset: 0
Model: HD
Phone: False
loglevel: verbose
subsample: 1
output_fmt: json
=======================================
/usr/local/bin/ffmpeg -y -hide_banner -stats -loglevel verbose  -i "./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p.mp4" -i "./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_1080p_50M.mp4" -map 0:v -map 1:v -lavfi "[0:v]scale=1920:1080:flags=bicubic[input0_0];[input0_0]fps=fps=30.0[input0_1];[1:v]fps=fps=30.0[input1_0];[input0_1][input1_0]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p_vmaf.json:psnr=1:ssim=1" -f null -
=======================================
VMAF computed
=======================================
offset:  0  | psnr:  None
VMAF score (arithmetic mean):  37.948279865277776
VMAF score (harmonic mean):  37.42345926938661
VMAF output File Path:  ./Beauty_3840x2160_120fps_420_8bit_YUV_RAW/Beauty_3840x2160_30fps_pass2/Beauty_3840x2160_100kkbps_240p_vmaf.json

**Comment by minhkstn** [comment]
Sorry, i didn't pull your latest version of source code. Now the VMAF for phone is 56.934366 and for HD model is 37.948280

Thank you for your time!
