### ISSUE TITLE
Calculating VMAF for two variable framerate videos gives strange results

### ISSUE THREAD

**Issue by Snelso91** [gdavila/easyVmaf#14]
I have recently tried to use the easyVMAF docker image on windows to try and compare two videos - the source file (a 1080p HEVC/H265 video with variable framerate), and the distorted file (a 1080p AVC1/H264 video also with variable framerate) which was transcoded from the source using handbrake. Both videos have a target framerate of 60fps, but they have different minimum and maximum framerates.

The variable framerate of the videos seems to have caused a syncing issue between the files, where some of the frames are out of sync in the distorted video relative to the source video and vice-versa.
The reason I noticed this is that there are several frames throughout the VMAF json log (converted to txt to upload to github) that have a score of 0. And if I manually scroll through the two files in a video player and go to the same frame numbers on both files, then sometimes (but not always) the frames will be out of sync by one frame. For example, frames 0-5 are all in sync, but by frame 601 they are out of sync by 1 frame, and by frame 2106 they are in sync again.

Is there some kind of option or filter in easyVMAF to sync these variable framerates correctly?

I have seen an [answer to a similar question](https://github.com/Netflix/vmaf/issues/155#issuecomment-491032458) on the official VMAF github suggesting that ffmpeg can be used to temporarily convert the variable framerate input videos into constant framerate versions, but I am not sure how to do this within easyVMAF as I can't see any easyVMAF flags for ffmpeg operations like that?

[VMAF json log.txt](https://github.com/gdavila/easyVmaf/files/7884087/GAME.OF.THE.YEAR.420.BLAZE.IT.Compilation.RF14.High.Auto_vmaf.txt)
[easyVMAF Windows CMD Log.txt](https://github.com/gdavila/easyVmaf/files/7884061/easyVMAF.Log.txt)

**Comment by gdavila** [comment]
Hi,

Unfortunately easyVmaf doesn't provide a way to compute vmaf for variable frame rate assets. It should be easy to add an additional flag for ffmpeg to set fixed frame rate  but I'm not sure on how that will impact on the vmaf scores  and I don't have enough time to do some tests  for the following weeks. Usually frame rate conversion is not suggested for VMAF computations if you want confidence on the score. 

Have you considered to change the frame rate before doing the computations?

**Comment by Snelso91** [comment]
Hi,

Other than using the ffmpeg flag to do the framerate conversion on the fly without transcoding as VMAF is running, I also considered changing both the source file and distorted file to constant frame rate before doing the comparison, but the only way I can think of doing this would be to transcode them both with handbrake (or at least transcode the source file since the distorted file can be set to be constant frame rate when it is created in handbrake), but wouldn't this cause some data loss since H265 and H264 are both lossy formats?

On the other hand, I've seen some suggestion that using CRF/quality factor 0 in handbrake can accomplish lossless H264/H265 albeit [only for 8 bit video](https://stackoverflow.com/questions/47949486/is-h-264-used-with-crf-0-really-strictly-lossless).
If it is true that CRF 0 = lossless then I could temporarily transcode the source file before comparing to create a fixed frame rate source file, and then delete the CRF 0 file afterwards (as it would be much larger than the original and an unnecessary copy to keep around long term).

Is this what you were suggesting or have I misunderstood?

EDIT: After testing with transcoding the variable framerate H265 file to CRF0 (supposedly "lossless") H264 constant framerate I can confirm that this is not a fully lossless operation in Handbrake as on certain frames I can notice a slight amount of blurring has been added by the transcode that was not in the original file.

**Comment by gdavila** [comment]
I would need to double check it but as far as I remember, using the the cmd ` ffmpeg -i <input> -filter:v fps=fps=60 <output>` to change the frame rate and then using the `<output>` file  as VMAF input produced the same result as applying the fps directly together with vmaf filter. So my suspicion is that a transcoding is always involved when doing frame rate conversion, and that is the main reason why  it is nor recommended to do so.

**Comment by Snelso91** [comment]
Ok, but if using the fps filter at runtime produces the same result as separately losslessly transcoding, then surely using the filter at 
 runtime is a better option since first of all the user doesn't need to run a separate command outside of easyVMAF (I'm assuming that easyVMAF would be able to detect VFR video via ffmpeg and then automatically apply the CFR filter to it), and also you don't end up with a large losslessly transcoded file in addition to your source file taking up space on your hard drive?

**Comment by gdavila** [comment]
Yes, also CRF is not needed. I did some tests in the past, what I did was to add a fps filter to the filter chain that  easyVMAF uses to do all the pre-processing: upscaling, downscaling, interlacing, etc. framerate conversion would be one  more filter. 

Perhaps the easiest way to implement this, is leaving to the user to force a fps conversion when needed instead of detecting VRF. I've seen that the metadata to detect VFR is not always well signaled and ffprobe not always get the actual information.

**Comment by Snelso91** [comment]
Yes, I agree that at least having a manual option to activate ffmpeg fps conversion in easyVMAF for VFR material would be helpful.

Regarding how to do it automatically, would it be possible to set a filter similar to "fps=average fps", where average fps is the number reported by ffmpeg or mediainfo or similar?
That way, if the video is CFR then the framerate will not be changed since you are setting the fps filter to the same as the original fps, but for VFR video it would then apply the fps filter to make the output CFR with the same average framerate as the original?

**Comment by gdavila** [comment]
> would it be possible to set a filter similar to "fps=average fps", where average fps is the number reported by ffmpeg or mediainfo or similar?

Yeah, that is feasible. I tried this approach in the past. The only caveat was that some times the reported fps was not accurate so an unnecessary  framerate conversion was forced by mistake and this changed the vmaf scores. 


> That way, if the video is CFR then the framerate will not be changed since you are setting the fps filter to the same as the original fps, but for VFR video it would then apply the fps filter to make the output CFR with the same average framerate as the original?

Same issue I mentioned before. Let's suppose that the actual fps is 1/30. Some times the reported fps shows 0.333 (not all decimals) so is hard to know a priori if the reported  fps is the real one or just a bad approximation.

On my previous job I had access to a wide variety of encoders so I could check all this behaviours - I don't have access  to them any more and that is why I leave this without a definitive solution. 

As next step I will add the manual fps as it is pretty easy. :)

**Comment by Snelso91** [comment]
Alright, I think that's a good option until ffmpeg fps detection becomes more reliable :)

**Comment by gdavila** [comment]
Manually setting the` fps` to force a manual frame rate conversion has been implemented on commit a3143a45a2fb82a871f91e31faa264b580a1dd26.
