### ISSUE TITLE
easyVmaf crashes when using file names with spaces and -progress flag

### ISSUE THREAD

**Issue by Snelso91** [gdavila/easyVmaf#16]
When using the -progress flag from the new release and a source or distorted file with spaces in the filename (even with the filenames in double quotes when running the command), easyVmaf running in docker crashes with the error:

`['/usr/local/bin/ffmpeg', '-y', '-hide_banner', '-stats', '-loglevel', 'info', '-i', '"/VMAF-Docker/Distorted', 'Test.mp4"', '-i', '"/VMAF-Docker/Reference.mp4"', '-map', '0:v', '-map', '1:v', '-lavfi', '"[0:v]fps=fps=60.0[input0_0];[1:v]fps=fps=60.0[input1_0];[input0_0][input1_0]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=/VMAF-Docker/Distorted', 'Test_vmaf.json:n_threads=16"', '-f', 'null', '-'] ['/usr/local/bin/ffmpeg', '-y', '-hide_banner', '-stats', '-loglevel', 'info', '-i', '/VMAF-Docker/Distorted', 'Test.mp4', '-i', '/VMAF-Docker/Reference.mp4', '-map', '0:v', '-map', '1:v', '-lavfi', '[0:v]fps=fps=60.0[input0_0];[1:v]fps=fps=60.0[input1_0];[input0_0][input1_0]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=/VMAF-Docker/Distorted', 'Test_vmaf.json:n_threads=16', '-f', 'null', '-']
Traceback (most recent call last):
  File "easyVmaf.py", line 144, in <module>
    vmafProcess = myVmaf.getVmaf()
  File "/app/easyVmaf-master/Vmaf.py", line 378, in getVmaf
    vmafProcess = self.ffmpegQos.getVmaf(model = self.model, phone = self.phone, subsample= self.subsample, output_fmt=self.output_fmt, threads=self.threads, print_progress= self.print_progress)
  File "/app/easyVmaf-master/FFmpeg.py", line 177, in getVmaf
    for progress in process.run_command_with_progress():
  File "/root/.local/lib/python3.8/site-packages/ffmpeg_progress_yield/ffmpeg_progress_yield.py", line 86, in run_command_with_progress
    raise RuntimeError(
RuntimeError: Error running command ['/usr/local/bin/ffmpeg', '-y', '-hide_banner', '-stats', '-loglevel', 'info', '-i', '/VMAF-Docker/Distorted', 'Test.mp4', '-i', '/VMAF-Docker/Reference.mp4', '-map', '0:v', '-map', '1:v', '-lavfi', '[0:v]fps=fps=60.0[input0_0];[1:v]fps=fps=60.0[input1_0];[input0_0][input1_0]libvmaf=log_fmt=json:model_path=/usr/local/share/model/vmaf_v0.6.1.json:phone_model=0:n_subsample=1:log_path=/VMAF-Docker/Distorted', 'Test_vmaf.json:n_threads=16', '-f', 'null', '-']: /VMAF-Docker/Distorted: No such file or directory
`

I confirmed that this does not happen if the filename has no spaces (even if the video directory path has spaces on the host system/outside of docker), and it also does not occur if spaces are used but the -progress flag is removed from the command.

Cmd log file attached [here](https://github.com/gdavila/easyVmaf/files/7953865/easyVmaf.-progress.space.error.cmd.exe.log.txt).

**Comment by gdavila** [comment]
Solved in https://github.com/gdavila/easyVmaf/commit/f44b1c04da6eedb8bab14eb88ae78976dcc0ddc2
