### ISSUE TITLE
log and JSON output doesn't match

### ISSUE THREAD

**Issue by rbronco21** [gdavila/easyVmaf#17]
<pre>VMAF scores in my log and the JSON files don't match. I'm running this from your docker on an unraid server. There's a (good) chance this is my own doing, but I can't see what I can change that could make any difference. I've been running high subsamples to run quick tests. I wanted to put this in a discussion before making it an issue, but I guess discussions are an option you have to enable?

Arguments:
-d /videos/est.x264.mkv -r /videos/Test.mpg -sw 0.1 -subsample 120

Log:
=======================================
VMAF computed
=======================================
offset: 0.03336666666666667 | psnr: 31.173307
VMAF score (arithmetic mean): 95.01512625
VMAF score (harmonic mean): 94.98438933581139
VMAF output File Path: /videos/Test.x264_vmaf.json

JSON out:
      "min": 89.523469,
      "max": 93.736860,
      "mean": 91.630165,
      "harmonic_mean": 91.582252</pre>

**Comment by gdavila** [comment]
Hi,

Thanks for reporting this. Could you upload a sample asset that allows me to reproduce the issue? Could you also double check you are running the last docker image?

**Comment by rbronco21** [comment]
It looks like it only happens with a subsample other than 1.

[easyVmaf.zip](https://github.com/gdavila/easyVmaf/files/8044488/easyVmaf.zip)

**Comment by gdavila** [comment]
It seems a vmaf issue. For some reason when setting the subsample option, the aggregated metrics from the json file generated by vmaf get broken. The aggregated  metrics generated by easyVmaf are the actual ones.

Take into account that the docker image is not using the last ffmpeg/vmaf version.

**Comment by rbronco21** [comment]
Do you use these versions for a reason? Any plans for an update? I'm new to this but don't mind playing around a bit. Is it just a matter of updating the dockerfile with different versions? I'm guessing newer versions may also change syntax and your scripts may need some adjustments as well?

**Comment by gdavila** [comment]
Ffmpeg v4.2 was the latest stable release I was able to test carefully that worked good enough with Vmaf 2.0. Now ffmpeg v5 is available but there are still a couple of opened issues regarding VMAF usage. 

If you update the Docker file to the latest ffmpeg v4 version, the same sintaxis should work. However, if you want to test  it with ffmpeg v5, some changes may be needed.


Also, take into account that only the aggregated metrics are wrong, you could compute them by yourself using the frame by frame info from the json file.

**Comment by gdavila** [comment]
Closing this ticket as this was a bug from ffmpeg 4.2 and to from easvmaf
