### ISSUE TITLE
easyvmaf generates incorrect vmaf with `yuv422p10le` format

### ISSUE THREAD

**Issue by oscnord** [gdavila/easyVmaf#18]
Currently running the latest docker image and getting incorrect vmaf measures with 10bit (yuv422p10le) content. However upgrading ffmpeg/libvmaf to latest version seems to fix these issues. 

See: 
- https://github.com/Netflix/vmaf/issues/211 for related issue. 
- https://github.com/FFmpeg/FFmpeg/commit/e835a9d30263ce16e2621d79ff1be9afd5274a60#diff-a5ec317d1bbe660634497cb981cda18f

**Comment by oscnord** [comment]
Did a reinstall from master and everything seems to be working as it should.

**Comment by oscnord** [comment]
Reopening this issue because it actually looks like FFmpeg `v5.0` is needed or at least a version with the patch above when using the image from docker hub which currently is running `v4.2.2`. Running this locally without docker however of course works fine with a newer version of FFmpeg.

**Comment by gdavila** [comment]
Can you upload a short sample file with  `yuv422p10le` format? so I can play a bit with this issue.

**Comment by oscnord** [comment]
> Can you upload a short sample file with `yuv422p10le` format? so I can play a bit with this issue.

I don't have any content that I can share publicly here but I'll try to get my hands on a short clip if I can. Would it be possible to share it with you via email for example?

**Comment by gdavila** [comment]
sure, [here](mailto:gdavila.revelo@gmail.com) is my email.

**Comment by gdavila** [comment]
Closing this ticket as the issue seems:

- to be related with vmaf/ffmpeg versions
- no sample files to reproduce the issue were provided
