### ISSUE TITLE
Runtime error if no 'duration' in stream info

### ISSUE THREAD

**Issue by balaccord** [gdavila/easyVmaf#2]
Hi

Got error in line 69 of Vmaf.py when comparing my MKVs

Very quick and dirty patchwork. If no 'duration' in the 'stream' then take it from the 'format'. It hides the problem instead of solving but it is

```
diff --git a/FFmpeg.py b/FFmpeg.py
index 83b5c80..c330cfe 100644
--- a/FFmpeg.py
+++ b/FFmpeg.py
@@ -59,8 +59,12 @@ class FFprobe:

     ''' public methods '''
     def getStreamInfo(self):
-        self._commit('-show_streams')
-        self.streamInfo = self._run()['streams'][0]
+        self._commit('-show_format -show_streams')
+        info = self._run()
+        streaminfo = info['streams'][0]
+        if not 'duration' in streaminfo:
+            streaminfo['duration'] = info['format'].get('duration', 0)
+        self.streamInfo = streaminfo
         return self.streamInfo

     def getFramesInfo(self):
```

**Comment by gdavila** [comment]
Hi, thanks a lot for the feedback!

I'm not familiar with mkv container. The issue would be related with all mkv or with some video samples? 

If you could you help me with a video sample or at least with the output of `ffprobe  -show_format -show_stream your_video_sample.mkv`, it would be great.

**Comment by balaccord** [comment]
Have no even a tiniest idea whether all of them have not this field or only mine do :) I'm only running ffmpeg and it's writing something by it's own. I never studied the matroska internals and just use it as the container that is less constrained than it's rivals

Comparison of video container formats
https://en.wikipedia.org/wiki/Comparison_of_video_container_formats

All in all I want to transcode my family video into the somethong more compact for the archival purpose. The destination format is _always_ MKV for I like it

I hope my patch doesn't make the things much worse. If the tag is already presented in the video stream, it just does nothing

The file you asked for
[ffprobe_my_video_out.txt](https://github.com/gdavila/easyVmaf/files/4978932/ffprobe_my_video_out.txt)

P.S. btw it's a bit of strange: audio and subrip streams have 'duration', 'format' has, too, but video has not. Again, have no idea why it's so :)

**Comment by gdavila** [comment]
I noticed that most  .mkv containers has no duration field on it video stream. So I have changed the way the duration info is got by using `format` information instead of `stream` info.

**Comment by balaccord** [comment]
Sorry, I think it's more preferrable to get the duration from the format ONLY if it is not in the stream itself. Because In general the durations should not be equal. For example, wonder what the stunts my "beloved" Sony camera does: the video and the format durations are completely different thus the `start_time` is added to sync video with audio
[20191011-154902-00003.MTS.txt](https://github.com/gdavila/easyVmaf/files/5003398/20191011-154902-00003.MTS.txt)

Probably it takes the time to start the video recording while the audio's starting at once. Or any other cause

**Comment by gdavila** [comment]
You are definitely right. I have added a `try`,  `catch` to handle this issue in a more proper way in a separate function.
I already had to work on some workarounds to get the stream duration for other formats so I think the best alternative for now is isolating the duration computation in a separate function. 

```py
    def getDuration(self):
        try:
            duration = round(float(self.streamInfo['duration'])-float(self.streamInfo['start_time']))
            if duration < 0:
                duration = round(float(self.streamInfo['duration']))
        except KeyError:
            duration = round(float(self.formatInfo['duration'])-float(self.formatInfo['start_time']))
            if duration < 0:
                duration = round(float(self.formatInfo['duration']))
        return duration
```

**Comment by balaccord** [comment]
Now it looks good for me :)

Just in case: there may be the other drawbacks though even if handling of the headers is ok. The frame rate way be floating, the frame doubling or skipping may occur and the heaven only knows what else could it be. Though the VMAF demands **the exact** positioning, So in these cases the only way to get the proper duration is to use, say, ffmpeg decoding in the null mode

The citation from the ffmpeg wiki http://trac.ffmpeg.org/wiki/FFprobeTips

`ffmpeg -i input.webm -f null -`

> This method will report the correct duration in case the methods shown above using ffprobe are incorrect or missing due to corrupt, truncated, or damaged files

I'm now thinking about the alike problem: how to get known the **exact** number of frames and how to start ffmpeg piping/transcoding **exactly** from the known frame number, preferrably without the full decoding from the very start? When I know for sure that the files contain _something_ so ffmpeg skips some frames. Kinda Av1an but without the intermediate disk files, on the fly
