### ISSUE TITLE
Deprecated options used in ffmpeg

### ISSUE THREAD

**Issue by miguelapg** [gdavila/easyVmaf#20]
[libvmaf @ 0000023174766a40] The "model_path" option is deprecated: use model='path=...'.
    Last message repeated 1 times
[libvmaf @ 0000023174766a40] The "phone_model" option is deprecated: use model='enable_transform=true'.
[libvmaf @ 0000023174766a40] The "model_path" option is deprecated: use model='path=...'.
[libvmaf @ 0000023174766a40] The "phone_model" option is deprecated: use model='enable_transform=true'.
[libvmaf @ 0000023174766a40] The "model_path" option is deprecated: use model='path=...'.

**Comment by gdavila** [comment]
Fixed in https://github.com/gdavila/easyVmaf/commit/3e885826f59f04844911a68740c956cb939180a5
