### ISSUE TITLE
maybe basic questions from an audio guy

### ISSUE THREAD

**Issue by listener17** [gdavila/easyVmaf#21]
I'm an audio guy, I have a few basic questions: 

- If I think from a matrix point of view, what is the minimum and maximum matrix dimensions of an image that can be fed to VMAF?
- What's the input image format? Can I just feed in (ref.-deg. pair of) 1-channel of the image? 
- Is there an example to run the VMAF on some image?

**Comment by gdavila** [comment]
Hi @listener17 

- easyVmaf is just a wrapper of ffmpeg + vmaf. For a more clear understanding about what VMAF is, I suggest you to start with official  vmaf documentation https://github.com/Netflix/vmaf
- However, I don't think that vmaf can be used for images only as vmaf was strictly focused on video streams so it considers how human visual system reacts to space-temporal artifacts.
- YUV is the default format, but you can use ffmpeg to convert compressed video sequences  to YUV sequences
- YUV images have tree components/channels but vmaf only uses one of them (Y- luminance)
