### ISSUE TITLE
Option model not found

### ISSUE THREAD

**Issue by tskamaldeep** [gdavila/easyVmaf#23]
Please review the below instance of error when running the script directly.

Running following command on Mac terminal, with ffmpeg5 installed:
$ python3 easyVmaf.py -d distorted.mp4 -r ref.mp4 -sw 2

[Parsed_libvmaf_2 @ 0x7fde1442f140] Option 'model' not found
[AVFilterGraph @ 0x7fde14438040] Error initializing filter 'libvmaf' with args 'log_fmt=json:model=version=vmaf_v0.6.1\:name=vmaf_hd|version=vmaf_v0.6.1neg\:name=vmaf_hd_neg|version=vmaf_v0.6.1\:name=vmaf_hd_phone\:enable_transform=true:n_subsample=1:log_path=vmaf.json:n_threads=4:shortest=0:feature=name=psnr|name=cambi\:full_ref=true\:enc_width=1920\:enc_height=1080\:src_width=1920\:src_height=1080'

Error initializing complex filters.
Option not found

Traceback (most recent call last):
  File "/../github/easyVmaf/easyVmaf.py", line 174, in <module>
    with open(vmafpath) as jsonFile:
FileNotFoundError: [Errno 2] No such file or directory:

**Comment by gdavila** [comment]
What ffmpeg version are you using?

I got the same error when running the latest stable ffmpeg (v5.0.1) via homebrew. It was solved when tried with the snapshot builds https://evermeet.cx/pub/ffmpeg/snapshots/ . It seemed  a ffmpeg issue.

Let me know if moving to the latest snapshot works

**Comment by tskamaldeep** [comment]
Thanks! I can confirm that the latest evermeet snapshot build does not have the mentioned issue.
