### ISSUE TITLE
Unsupported codec with id 0 for input stream 2

### ISSUE THREAD

**Issue by saltarob** [gdavila/easyVmaf#29]
Hi,

great tool! Thank you so much.

Unfortunately with certain files I get the "Unsupported codec with id 0 for input stream 2" warning. 
It showed up with a Sony XAVC encoded recording in a mp4 container and ProRes in a mov container.

The files are playing fine with FFplay. Where is the codec limitation coming from and which codecs are supported and which not? 

Thank you.

**Comment by gdavila** [comment]
Hi @saltarob 

EasyVmaf is just an ffmpeg wrapper so any constraint on supported codecs are ffmpeg related. However, given that your file  plays with ffmpeg maybe easyvmaf is doing something wrong, ie,  trying to compute  vmaf scores for a non video stream (id=0). Can you share a sample file and the ffprobe output?

**Comment by saltarob** [comment]
Hi @gdavila,

thank you so much for your answer.
Following the ffprobe output:

`% ffprobe /Users/abdulhadi/Downloads/C0001_20230603_13-54-33.MP4 
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/6.0-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --enable-opencl --enable-audiotoolbox --enable-videotoolbox --disable-htmlpages --enable-libsrt --enable-libvmaf --enable-version3
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/abdulhadi/Downloads/C0001_20230603_13-54-33.MP4':
  Metadata:
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2023-06-03T10:54:33.000000Z
  Duration: 00:13:37.44, start: 0.000000, bitrate: 51632 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 49889 kb/s, 25 fps, 25 tbr, 25k tbn (default)
    Metadata:
      creation_time   : 2023-06-03T10:54:33.000000Z
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2023-06-03T10:54:33.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (rtmd / 0x646D7472), 204 kb/s (default)
    Metadata:
      creation_time   : 2023-06-03T10:54:33.000000Z
      handler_name    : Timed Metadata Media Handler
      timecode        : 04:21:54:06
Unsupported codec with id 0 for input stream 2`

And a short sample of the video:

 

https://github.com/gdavila/easyVmaf/assets/7444144/cf65806b-2740-4eb9-b5dc-8b8789c8e139

**Comment by orion486** [comment]
As it was pointed out earlier, this is not an easyVmaf issue but your file containing a codec that ffmpeg doesn't support yet. Let's take a look at your ffprobe output:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/abdulhadi/Downloads/C0001_20230603_13-54-33.MP4':
  Metadata: 
    major_brand     : XAVC
    minor_version   : 16785407
    compatible_brands: XAVCmp42iso2
    creation_time   : 2023-06-03T10:54:33.000000Z 
  Duration: 00:13:37.44, start: 0.000000, bitrate: 51632 kb/s 
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 49889 kb/s, 25 fps, 25 tbr, 25k tbn (default)
    Metadata: 
    creation_time   : 2023-06-03T10:54:33.000000Z 
    handler_name    : Video Media Handler 
    vendor_id       : [0][0][0][0] 
    encoder         : AVC Coding 
  Stream #0:1[0x2](und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default) 
    Metadata: 
    creation_time   : 2023-06-03T10:54:33.000000Z 
    handler_name    : Sound Media Handler 
    vendor_id       : [0][0][0][0] 
  Stream #0:2[0x3](und): Data: none (rtmd / 0x646D7472), 204 kb/s (default) 
    Metadata: 
    creation_time   : 2023-06-03T10:54:33.000000Z 
    handler_name    : Timed Metadata Media Handler
    timecode        : 04:21:54:06
    Unsupported codec with id 0 for input stream 2
```
Notice that at the very last line it says that the last stream uses an unsupported codec by `Timed Metadata Media Handler` with FourCC `rtmd`. Luckily, that codec seems like it's not needed for playback as your video and audio streams use recognized codecs. The solution to this is to remove that last stream with a command like the following and use that new file with easyVmaf:
``` shell
$ ffmpeg -hide_banner \
-i /Users/abdulhadi/Downloads/C0001_20230603_13-54-33.MP4 \
-map -0:2 \
-c copy \
/Users/abdulhadi/Downloads/C0001_20230603_13-54-33_noRtmd.mp4
```

**Comment by saltarob** [comment]
Hi, thank you so much for the clarification and the solution.
Wish you the best.

**Comment by gdavila** [comment]
Thanks @orion486 for picking it up.
