### ISSUE TITLE
XML parser is missing 

### ISSUE THREAD

**Issue by PhilippeR** [gdavila/easyVmaf#6]
Since the last release, code for xml parsing in easyvmaf.py has disappeared

`        if output_fmt == 'json':
            with open(vmafpath) as jsonFile:
                jsonData = json.load(jsonFile)
                for frame in jsonData['frames']:
                    vmafScore.append(frame["metrics"]["vmaf"])
                vmafScoreMean = mean(vmafScore)
        else:
            tree = ET.parse(vmafpath)
            root = tree.getroot()
            for frame in root.findall('frames/frame'):
                value = frame.get('vmaf')
                print(value)
                vmafScore.append(float(value))
            vmafScoreMean = (sum(vmafScore) / len(vmafScore)) `

**Comment by gdavila** [comment]
Oh, my fault!

It was a conflict between [PR4](https://github.com/gdavila/easyVmaf/pull/4) and [PR3](https://github.com/gdavila/easyVmaf/pull/3). So I guess I delete accidentally that portion of the code trying to solve it. Could you add it to the last commit and create a new PR?

**Comment by gdavila** [comment]
@PhilippeR The harmonic mean is not being computed on the last PR but still being printed. I noticed just once I merged it. See [easyVmaf.py#L159](https://github.com/gdavila/easyVmaf/blob/bd69fc87c277da50087802e834afdfdf0520e71e/easyVmaf.py#L159)
