### ISSUE TITLE
-model 4k returns error

### ISSUE THREAD

**Issue by menaceone** [gdavila/easyVmaf#8]
I use your nice tool via docker and with default settings it just works fine.
However, with the `-model` parameter I get an Error:  
`[easyVmaf] ERROR: Invalid vmaf model`

My complete cmds i tried:  
* `docker run -v /mnt/video-samples:/video-samples gfdavila/easyvmaf -r /video-samples/reference.mxf -d /video-samples/distorted.mp4 -model 4k`
* `docker run -v /mnt/video-samples:/video-samples gfdavila/easyvmaf -r /video-samples/reference.mxf -d /video-samples/distorted.mp4 -model "4k"`
* `docker run -v /mnt/video-samples:/video-samples gfdavila/easyvmaf -r /video-samples/reference.mxf -d /video-samples/distorted.mp4 -model '4k'`
* `docker run -v /mnt/video-samples:/video-samples gfdavila/easyvmaf -r /video-samples/reference.mxf -d /video-samples/distorted.mp4 -model='4k'`

**Comment by gdavila** [comment]
Try with 4K (in capital letters) `-model 4K`. I should **convert all the inputs to lower/upper case** to avoid these missunderstandings.

**Comment by menaceone** [comment]
Indeed it's in capital. Just as correctly stated in your README.
Thanks a lot!
